title: Research Data Management ontology (RDM ontology) Usage Guidelines
description: Guidelines for using the Research Data Management ontology (RDM ontology)
baseurl: "/rdm"
url: "https://rcosdp.github.io"

remote_theme: pages-themes/minimal@v0.2.0

plugin:
  - jekyll-toc
  - jekyll-remote-theme

toc:
  min_level: 2
  ordered_list: false

defaults:
  - scope:
      path: ""
    values:
      toc: true
